class Autogenerated {
  List<Success> success;
  int status;

  Autogenerated({this.success, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['success'] != null) {
      success = new List<Success>();
      json['success'].forEach((v) {
        success.add(new Success.fromJson(v));
      });
    }
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.success != null) {
      data['success'] = this.success.map((v) => v.toJson()).toList();
    }
    data['status'] = this.status;
    return data;
  }
}

class Success {
  int id;
  int userId;
  String status;
  String name;
  String address;
  String phone;
  int qty;
  String total;
  Null txnId;
  Null paymentStatus;
  String createdAt;
  String updatedAt;
  List<Orderitems> orderitems;

  Success(
      {this.id,
      this.userId,
      this.status,
      this.name,
      this.address,
      this.phone,
      this.qty,
      this.total,
      this.txnId,
      this.paymentStatus,
      this.createdAt,
      this.updatedAt,
      this.orderitems});

  Success.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    status = json['status']==null?json['status']:"".toString();
    name = json['name'];
    address = json['address'];
    phone = json['phone'];
    qty = json['qty'];
    total = json['total'];
    txnId = json['txn_id'];
    paymentStatus = json['payment_status'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['orderitems'] != null) {
      orderitems = new List<Orderitems>();
      json['orderitems'].forEach((v) {
        orderitems.add(new Orderitems.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    data['status'] = this.status;
    data['name'] = this.name;
    data['address'] = this.address;
    data['phone'] = this.phone;
    data['qty'] = this.qty;
    data['total'] = this.total;
    data['txn_id'] = this.txnId;
    data['payment_status'] = this.paymentStatus;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.orderitems != null) {
      data['orderitems'] = this.orderitems.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Orderitems {
  int id;
  int orderId;
  int productId;
  int quantity;
  String price;
  String createdAt;
  String updatedAt;
  String expiryDate;
  ProductInfo productInfo;
  ProductInfo product;

  Orderitems(
      {this.id,
      this.orderId,
      this.productId,
      this.quantity,
      this.price,
      this.createdAt,
      this.updatedAt,
      this.expiryDate,
      this.productInfo,
      this.product});

  Orderitems.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    orderId = json['order_id'];
    productId = json['product_id'];
    quantity = json['quantity'];
    price = json['price'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    expiryDate = json['expiry_date'];
    productInfo = json['ProductInfo'] != null
        ? new ProductInfo.fromJson(json['ProductInfo'])
        : null;
    product = json['product'] != null
        ? new ProductInfo.fromJson(json['product'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['order_id'] = this.orderId;
    data['product_id'] = this.productId;
    data['quantity'] = this.quantity;
    data['price'] = this.price;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['expiry_date'] = this.expiryDate;
    if (this.productInfo != null) {
      data['ProductInfo'] = this.productInfo.toJson();
    }
    if (this.product != null) {
      data['product'] = this.product.toJson();
    }
    return data;
  }
}

class ProductInfo {
  int id;
  String productName;
  String productImage;
  String sku;
  int stockQuantity;
  Null qty;
  String productPrice;
  Null otherPrice;
  int productCategory;
  String productDescription;
  int userId;
  Null verified;
  int renewalAmount;
  int duration;

  ProductInfo(
      {this.id,
      this.productName,
      this.productImage,
      this.sku,
      this.stockQuantity,
      this.qty,
      this.productPrice,
      this.otherPrice,
      this.productCategory,
      this.productDescription,
      this.userId,
      this.verified,
      this.renewalAmount,
      this.duration});

  ProductInfo.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    productName = json['product_name'];
    productImage = json['product_image'];
    sku = json['sku'];
    stockQuantity = json['stock_quantity'];
    qty = json['qty'];
    productPrice = json['product_price'];
    otherPrice = json['other_price'];
    productCategory = json['product_category'];
    productDescription = json['product_description'];
    userId = json['user_id'];
    verified = json['verified'];
    renewalAmount = json['renewal_amount'];
    duration = json['duration'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['product_name'] = this.productName;
    data['product_image'] = this.productImage;
    data['sku'] = this.sku;
    data['stock_quantity'] = this.stockQuantity;
    data['qty'] = this.qty;
    data['product_price'] = this.productPrice;
    data['other_price'] = this.otherPrice;
    data['product_category'] = this.productCategory;
    data['product_description'] = this.productDescription;
    data['user_id'] = this.userId;
    data['verified'] = this.verified;
    data['renewal_amount'] = this.renewalAmount;
    data['duration'] = this.duration;
    return data;
  }
}